baseURL = "https://centropineal.com.br"
disqusShortname = ""
languageCode = "pt-br"
paginate = 6
summaryLength = "10"
theme = "liva-hugo"
title = "Centro Pineal"
[[menu.footer]]
URL = "contact"
name = "Contato"
weight = 4
[[menu.footer]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.footer]]
URL = "about"
name = "Sobre"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contato"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "about"
name = "Sobre"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Centro Pineal"
copyright = "copyright &copy; Centro Pinel 2020 | Todos Direitos Reservados | [Themefisher](https://themefisher.com)"
description = "Centro Pineal"
email = "demo@email.com"
googleAnalitycsID = "Your ID"
home = "Home"
location = "Brasil"
logo = "images/logo.png"
mobile = "0124857985320"
[params.cookies]
enable = false
expire_days = 2
[params.newsletter]
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"
enable = false
title = "Join Our Newsletter"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-youtube"
link = "#"
title = "youtube"
